# Generated by Django 6.0.1 on 2026-01-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Уникальный код (slug)')),
                ('labor_coefficient', models.FloatField(default=1.0, verbose_name='Коэффициент сложности')),
            ],
            options={
                'verbose_name': 'Категория справочника',
                'verbose_name_plural': 'Категории справочника',
            },
        ),
        migrations.CreateModel(
            name='ContractorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок/Объект')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Запись подрядчика',
                'verbose_name_plural': 'Записи подрядчика',
            },
        ),
        migrations.CreateModel(
            name='EstimateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон сметы',
                'verbose_name_plural': 'Шаблоны смет',
            },
        ),
        migrations.CreateModel(
            name='LedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон LED',
                'verbose_name_plural': 'Шаблоны LED',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(choices=[('new_building', 'Новостройка'), ('secondary', 'Вторичка'), ('cottage', 'Коттедж'), ('office', 'Офис'), ('other', 'Другое')], default='new_building', max_length=20, verbose_name='Тип объекта')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('intercom_code', models.CharField(blank=True, max_length=20, verbose_name='Код домофона')),
                ('client_info', models.TextField(verbose_name='Контактные данные')),
                ('source', models.CharField(max_length=100, verbose_name='Источник объекта')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('calculating', 'Предпросчет'), ('stage1_done', 'Этап 1 готов'), ('stage2_done', 'Этап 2 готов'), ('stage3_done', 'Этап 3 готов'), ('completed', 'Завершен')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон щита',
                'verbose_name_plural': 'Шаблоны щитов',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена по умолчанию')),
                ('item_type', models.CharField(choices=[('work', 'Работа'), ('material', 'Материал')], default='material', max_length=20, verbose_name='Тип')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Справочник (Товары/Работы)',
            },
        ),
        migrations.CreateModel(
            name='LedTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Место установки/Лента')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ledtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона LED',
                'verbose_name_plural': 'Пункты шаблона LED',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
            },
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Главный щит', max_length=255, verbose_name='Название щита')),
                ('shield_type', models.CharField(choices=[('power', 'Силовой'), ('led', 'LED'), ('multimedia', 'Слаботочка')], default='power', max_length=20, verbose_name='Тип щита')),
                ('mounting', models.CharField(choices=[('internal', 'Внутренний (в нишу)'), ('external', 'Наружный (накладной)')], default='internal', max_length=20, verbose_name='Монтаж')),
                ('internet_lines_count', models.IntegerField(default=0, verbose_name='Кол-во интернет-линий')),
                ('multimedia_notes', models.TextField(blank=True, verbose_name='Заметки по мультимедиа')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shields', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Щит',
                'verbose_name_plural': 'Щиты',
            },
        ),
        migrations.CreateModel(
            name='LedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Место установки/Лента')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_zones', to='core.shield', verbose_name='Щит')),
            ],
            options={
                'verbose_name': 'Зона LED',
                'verbose_name_plural': 'Зоны LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('circuit_breaker', 'Автоматический выключатель'), ('diff_breaker', 'Диф.автомат'), ('rcd', 'УЗО'), ('relay', 'Реле напряжения'), ('contactor', 'Контактор'), ('load_switch', 'Выключатель нагрузки'), ('other', 'Другое')], default='circuit_breaker', max_length=20, verbose_name='Тип устройства')),
                ('rating', models.CharField(default='16A', max_length=50, verbose_name='Номинал')),
                ('poles', models.CharField(default='1P', max_length=50, verbose_name='Полюса')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='Устройство (Авто)')),
                ('zone', models.CharField(blank=True, max_length=255, verbose_name='Зона или потребитель')),
                ('modules_count', models.IntegerField(default=1, verbose_name='Кол-во модулей')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.shield', verbose_name='Щит')),
            ],
            options={
                'verbose_name': 'Группа щита',
                'verbose_name_plural': 'Группы щита',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство/Номинал')),
                ('zone', models.CharField(max_length=255, verbose_name='Зона/Потребитель')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shieldtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона щита',
                'verbose_name_plural': 'Пункты шаблона щита',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('precalc', 'Предпросчет'), ('stage_1', 'Этап 1 (Черновой)'), ('stage_1_2', 'Этап 1+2 (Черновой)'), ('stage_2', 'Этап 2 (Черновой)'), ('stage_3', 'Этап 3 (Чистовой)'), ('extra', 'Доп. работы'), ('other', 'Другое')], max_length=50, verbose_name='Название этапа')),
                ('status', models.CharField(choices=[('plan', 'План'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='plan', max_length=20, verbose_name='Состояние')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('work', 'Работа'), ('material', 'Материал')], max_length=20, verbose_name='Тип')),
                ('is_preliminary', models.BooleanField(default=False, verbose_name='Это предпросчет?')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за единицу')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта')),
                ('contractor_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кол-во подрядчика')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Из каталога')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='core.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Пункт сметы',
                'verbose_name_plural': 'Пункты сметы',
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во по умолчанию')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Элемент справочника')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.estimatetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона',
                'verbose_name_plural': 'Позиции шаблона',
            },
        ),
    ]
