# Generated by Django 6.0.1 on 2026-01-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('client_info', models.TextField(verbose_name='Контактные данные')),
                ('source', models.CharField(max_length=100, verbose_name='Источник объекта')),
                ('status', models.CharField(choices=[('precalculation', 'Предпросчет'), ('in_progress', 'В работе'), ('pause', 'Пауза'), ('completed', 'Завершен')], default='precalculation', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('stage_1', 'Этап 1 (Черновой)'), ('stage_2', 'Этап 2 (Подрозетники/Щиты)'), ('stage_3', 'Этап 3 (Чистовой)'), ('extra', 'Доп. работы')], max_length=50, verbose_name='Название этапа')),
                ('status', models.CharField(choices=[('plan', 'План'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='plan', max_length=20, verbose_name='Состояние')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('work', 'Работа'), ('material', 'Материал')], max_length=20, verbose_name='Тип')),
                ('is_preliminary', models.BooleanField(default=False, verbose_name='Это предпросчет?')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='core.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Пункт сметы',
                'verbose_name_plural': 'Пункты сметы',
            },
        ),
    ]
