# Generated by Django 6.0.1 on 2026-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта по умолчанию'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='employer_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Объем работодателя'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Наценка %'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий объем (для клиента)'),
        ),
    ]
