# Generated by Django 6.0.1 on 2026-01-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный код (slug)')),
                ('labor_coefficient', models.FloatField(default=1.0, verbose_name='Коэффициент сложности')),
            ],
            options={
                'verbose_name': 'Категория справочника',
                'verbose_name_plural': 'Категории справочника',
            },
        ),
        migrations.CreateModel(
            name='EstimateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон сметы',
                'verbose_name_plural': 'Шаблоны смет',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='project',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='project',
            name='intercom_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код домофона'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена по умолчанию')),
                ('item_type', models.CharField(choices=[('work', 'Работа'), ('material', 'Материал')], default='material', max_length=20, verbose_name='Тип')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Справочник (Товары/Работы)',
            },
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Из каталога'),
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во по умолчанию')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Элемент справочника')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.estimatetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона',
                'verbose_name_plural': 'Позиции шаблона',
            },
        ),
    ]
