# Generated by Django 6.0.1 on 2026-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalogcategory_estimatetemplate_project_entrance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок/Объект')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Запись подрядчика',
                'verbose_name_plural': 'Записи подрядчика',
            },
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='is_subcontractor',
            field=models.BooleanField(default=False, verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='object_type',
            field=models.CharField(choices=[('new_building', 'Новостройка'), ('secondary', 'Вторичка'), ('cottage', 'Коттедж'), ('office', 'Офис'), ('other', 'Другое')], default='new_building', max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('calculating', 'Предпросчет'), ('stage1_done', 'Этап 1 готов'), ('stage2_done', 'Этап 2 готов'), ('stage3_done', 'Этап 3 готов'), ('completed', 'Завершен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
