# Generated by Django 6.0.1 on 2026-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_estimateitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='Доп. работы'),
        ),
    ]
