# Generated by Django 6.0.1 on 2026-01-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contractornote_estimateitem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='is_subcontractor',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='contractor_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кол-во подрядчика'),
        ),
    ]
