# Generated by Django 6.0.1 on 2026-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estimateitem_is_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу'),
        ),
    ]
