# Generated by Django 6.0.1 on 2026-01-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estimateitem_is_subcontractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Место установки/Лента')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_zones', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Зона LED',
                'verbose_name_plural': 'Зоны LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство/Номинал')),
                ('zone', models.CharField(max_length=255, verbose_name='Зона/Потребитель')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shield_groups', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Группа щита',
                'verbose_name_plural': 'Группы щита',
            },
        ),
    ]
