# Generated by Django 6.0.1 on 2026-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_estimateitem_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='search_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поиск (нижний регистр)'),
        ),
    ]
