# Generated by Django 6.0.1 on 2026-01-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ledzone_shieldgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон LED',
                'verbose_name_plural': 'Шаблоны LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон щита',
                'verbose_name_plural': 'Шаблоны щитов',
            },
        ),
        migrations.CreateModel(
            name='LedTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Место установки/Лента')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ledtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона LED',
                'verbose_name_plural': 'Пункты шаблона LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство/Номинал')),
                ('zone', models.CharField(max_length=255, verbose_name='Зона/Потребитель')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shieldtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона щита',
                'verbose_name_plural': 'Пункты шаблона щита',
            },
        ),
    ]
