# Generated by Django 6.0.1 on 2026-01-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_catalogitem_search_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='is_extra',
        ),
    ]
