# Generated by Django 6.0.1 on 2026-01-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_estimateitem_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='material_notes',
            field=models.TextField(blank=True, verbose_name='Заметки по материалам'),
        ),
        migrations.AddField(
            model_name='stage',
            name='work_notes',
            field=models.TextField(blank=True, verbose_name='Заметки по работам'),
        ),
    ]
