# Generated by Django 6.0.1 on 2026-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ledtemplate_shieldtemplate_ledtemplateitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Уникальный код (slug)'),
        ),
    ]
