# Generated by Django 6.0.1 on 2026-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stage_material_notes_stage_work_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='material_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Наценка на материалы %'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_material_prices',
            field=models.BooleanField(default=False, verbose_name='Показывать цены на материалы'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='employer_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Объем контрагента'),
        ),
    ]
