# Generated by Django 6.0.1 on 2026-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_catalogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(choices=[('stage_1', 'Этап 1 (Черновой)'), ('stage_2', 'Этап 2 (Черновой)'), ('stage_3', 'Этап 3 (Чистовой)'), ('extra', 'Доп. работы')], max_length=50, verbose_name='Название этапа'),
        ),
    ]
