# Generated by Django 6.0.1 on 2026-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_stage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(choices=[('precalc', 'Предпросчет'), ('stage_1', 'Этап 1 (Черновой)'), ('stage_1_2', 'Этап 1+2 (Черновой)'), ('stage_2', 'Этап 2 (Черновой)'), ('stage_3', 'Этап 3 (Чистовой)'), ('extra', 'Доп. работы'), ('other', 'Другое')], max_length=50, verbose_name='Название этапа'),
        ),
    ]
