# Generated by Django 6.0.1 on 2026-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_material_markup_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='material_markup_percent',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='show_material_prices',
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='stage',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Наценка %'),
        ),
        migrations.AddField(
            model_name='stage',
            name='show_prices',
            field=models.BooleanField(default=False, verbose_name='Показывать цены?'),
        ),
    ]
