# Generated by Django 6.0.1 on 2026-01-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shieldgroup',
            name='device_type',
            field=models.CharField(choices=[('circuit_breaker', 'Автомат'), ('diff_breaker', 'Диф.автомат'), ('rcd', 'УЗО'), ('relay', 'Реле напряжения'), ('contactor', 'Контактор'), ('other', 'Другое')], default='circuit_breaker', max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='shieldgroup',
            name='modules_count',
            field=models.IntegerField(default=1, verbose_name='Кол-во модулей'),
        ),
        migrations.AddField(
            model_name='shieldgroup',
            name='poles',
            field=models.CharField(choices=[('1P', '1P'), ('2P', '2P'), ('3P', '3P'), ('4P', '4P')], default='1P', max_length=5, verbose_name='Полюса'),
        ),
        migrations.AddField(
            model_name='shieldgroup',
            name='rating',
            field=models.CharField(choices=[('6A', '6A'), ('10A', '10A'), ('16A', '16A'), ('20A', '20A'), ('25A', '25A'), ('32A', '32A'), ('40A', '40A'), ('50A', '50A'), ('63A', '63A')], default='16A', max_length=10, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='shieldgroup',
            name='device',
            field=models.CharField(blank=True, max_length=255, verbose_name='Устройство (Авто)'),
        ),
    ]
