# Generated by Django 6.0.1 on 2026-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shieldgroup_device_type_shieldgroup_modules_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shieldgroup',
            name='device_type',
            field=models.CharField(choices=[('circuit_breaker', 'Автоматический выключатель'), ('diff_breaker', 'Диф.автомат'), ('rcd', 'УЗО'), ('relay', 'Реле напряжения'), ('contactor', 'Контактор'), ('load_switch', 'Выключатель нагрузки'), ('other', 'Другое')], default='circuit_breaker', max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='shieldgroup',
            name='poles',
            field=models.CharField(default='1P', max_length=50, verbose_name='Полюса'),
        ),
        migrations.AlterField(
            model_name='shieldgroup',
            name='rating',
            field=models.CharField(default='16A', max_length=50, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='shieldgroup',
            name='zone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Зона или потребитель'),
        ),
    ]
