# Generated by Django 6.0.1 on 2026-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_stage_material_markup_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='material_remarks',
            field=models.TextField(blank=True, verbose_name='Примечания по материалам (для отчета)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='work_remarks',
            field=models.TextField(blank=True, verbose_name='Примечания по работам (для отчета)'),
        ),
    ]
