# Generated by Django 6.0.1 on 2026-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_shieldgroup_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internet_lines_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во интернет-линий'),
        ),
        migrations.AddField(
            model_name='project',
            name='multimedia_notes',
            field=models.TextField(blank=True, verbose_name='Заметки по мультимедиа'),
        ),
        migrations.AddField(
            model_name='project',
            name='suggested_internet_shield',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предполагаемый щиток слаботочки'),
        ),
    ]
