# Generated by Django 6.0.1 on 2026-01-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stage_material_remarks_stage_work_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='mapping_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Технический ключ'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='related_work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Связанная работа'),
        ),
    ]
