# Generated by Django 6.0.1 on 2026-01-31 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_catalogitem_mapping_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='aggregation_key',
            field=models.CharField(blank=True, help_text='Ключ группировки материалов. Используй формат agg_{название}, чтобы объединить этот материал с другими в одну работу.', max_length=100, null=True, verbose_name='Ключ агрегации'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='mapping_key',
            field=models.CharField(blank=True, help_text='Универсальный входной ключ. Для щитов: shield_{тип}{полюса}. Для работ: agg{название}.', max_length=100, null=True, verbose_name='Технический ключ'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='related_work_item',
            field=models.ForeignKey(blank=True, help_text='Прямая связь 1-к-1 (используется, если не задан aggregation_key).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Связанная работа'),
        ),
    ]
