# Generated by Django 6.0.1 on 2026-01-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_catalogitem_aggregation_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон материалов',
                'verbose_name_plural': 'Шаблоны материалов',
            },
        ),
        migrations.CreateModel(
            name='MultimediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон слаботочного щита',
                'verbose_name_plural': 'Шаблоны слаботочных щитов',
            },
        ),
        migrations.CreateModel(
            name='PowerShieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон силового щита',
                'verbose_name_plural': 'Шаблоны силовых щитов',
            },
        ),
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон работ',
                'verbose_name_plural': 'Шаблоны работ',
            },
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='ledtemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='ledtemplateitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='shieldtemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='shieldtemplateitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='catalog_item',
        ),
        migrations.CreateModel(
            name='MaterialTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во')),
                ('catalog_item', models.ForeignKey(limit_choices_to={'item_type': 'material'}, on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Материал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.materialtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона материалов',
                'verbose_name_plural': 'Позиции шаблона материалов',
            },
        ),
        migrations.CreateModel(
            name='MultimediaTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='Название/Устройство')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.multimediatemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция мультимедиа шаблона',
                'verbose_name_plural': 'Позиции мультимедиа шаблона',
            },
        ),
        migrations.CreateModel(
            name='PowerShieldTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('circuit_breaker', 'Автоматический выключатель'), ('diff_breaker', 'Диф.автомат'), ('rcd', 'УЗО'), ('relay', 'Реле напряжения'), ('contactor', 'Контактор'), ('load_switch', 'Выключатель нагрузки'), ('other', 'Другое')], default='circuit_breaker', max_length=20, verbose_name='Тип устройства')),
                ('rating', models.CharField(default='16A', max_length=50, verbose_name='Номинал')),
                ('poles', models.CharField(default='1P', max_length=50, verbose_name='Полюса')),
                ('zone', models.CharField(blank=True, max_length=255, verbose_name='Зона/Потребитель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.powershieldtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона силового щита',
                'verbose_name_plural': 'Позиции шаблона силового щита',
            },
        ),
        migrations.CreateModel(
            name='ShieldMultimediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название/Устройство')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_items', to='core.shield', verbose_name='Щит')),
            ],
            options={
                'verbose_name': 'Элемент слаботочки',
                'verbose_name_plural': 'Элементы слаботочки',
            },
        ),
        migrations.CreateModel(
            name='WorkTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во')),
                ('catalog_item', models.ForeignKey(limit_choices_to={'item_type': 'work'}, on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Работа')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.worktemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона работ',
                'verbose_name_plural': 'Позиции шаблона работ',
            },
        ),
        migrations.DeleteModel(
            name='EstimateTemplate',
        ),
        migrations.DeleteModel(
            name='LedTemplate',
        ),
        migrations.DeleteModel(
            name='LedTemplateItem',
        ),
        migrations.DeleteModel(
            name='ShieldTemplate',
        ),
        migrations.DeleteModel(
            name='ShieldTemplateItem',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
    ]
