# Generated by Django 6.0.1 on 2026-01-31 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_materialtemplate_multimediatemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон сметы',
                'verbose_name_plural': 'Шаблоны смет',
            },
        ),
        migrations.CreateModel(
            name='LedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон LED',
                'verbose_name_plural': 'Шаблоны LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон щита',
                'verbose_name_plural': 'Шаблоны щитов',
            },
        ),
        migrations.AlterModelOptions(
            name='multimediatemplate',
            options={'verbose_name': 'Шаблон мультимедиа', 'verbose_name_plural': 'Шаблоны мультимедиа'},
        ),
        migrations.AlterModelOptions(
            name='multimediatemplateitem',
            options={'verbose_name': 'Позиция мультимедиа', 'verbose_name_plural': 'Позиции мультимедиа'},
        ),
        migrations.AlterModelOptions(
            name='powershieldtemplateitem',
            options={'verbose_name': 'Позиция силового щита', 'verbose_name_plural': 'Позиции силового щита'},
        ),
        migrations.RemoveField(
            model_name='materialtemplateitem',
            name='default_quantity',
        ),
        migrations.RemoveField(
            model_name='multimediatemplateitem',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='powershieldtemplateitem',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='worktemplateitem',
            name='default_quantity',
        ),
        migrations.AddField(
            model_name='materialtemplateitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='multimediatemplateitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)'),
        ),
        migrations.AddField(
            model_name='multimediatemplateitem',
            name='name',
            field=models.CharField(default='Line', max_length=255, verbose_name='Название линии/устройства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powershieldtemplateitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)'),
        ),
        migrations.AddField(
            model_name='powershieldtemplateitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество (шт)'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialtemplateitem',
            name='catalog_item',
            field=models.ForeignKey(limit_choices_to={'item_type': 'material'}, on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Материал из каталога'),
        ),
        migrations.AlterField(
            model_name='multimediatemplateitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='worktemplateitem',
            name='catalog_item',
            field=models.ForeignKey(limit_choices_to={'item_type': 'work'}, on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Работа из каталога'),
        ),
        migrations.CreateModel(
            name='LedTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Место установки/Лента')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ledtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона LED',
                'verbose_name_plural': 'Пункты шаблона LED',
            },
        ),
        migrations.CreateModel(
            name='ShieldTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство/Номинал')),
                ('zone', models.CharField(max_length=255, verbose_name='Зона/Потребитель')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shieldtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона щита',
                'verbose_name_plural': 'Пункты шаблона щита',
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во по умолчанию')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalogitem', verbose_name='Элемент справочника')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.estimatetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция шаблона',
                'verbose_name_plural': 'Позиции шаблона',
            },
        ),
        migrations.DeleteModel(
            name='ShieldMultimediaItem',
        ),
    ]
