# Generated by Django 6.0.1 on 2026-01-31 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estimatetemplate_ledtemplate_shieldtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedShieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон LED-щита',
                'verbose_name_plural': 'Шаблоны LED-щитов',
            },
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='ledtemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='ledtemplateitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='multimediatemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='multimediatemplateitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='shieldtemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='shieldtemplateitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='catalog_item',
        ),
        migrations.AddField(
            model_name='ledzone',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='shieldgroup',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='LedShieldTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer', models.CharField(max_length=255, verbose_name='Трансформатор/Блок')),
                ('zone', models.CharField(max_length=255, verbose_name='Зона/Лента')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Товар (опционально)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ledshieldtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Позиция LED-щита',
                'verbose_name_plural': 'Позиции LED-щита',
            },
        ),
        migrations.DeleteModel(
            name='EstimateTemplate',
        ),
        migrations.DeleteModel(
            name='LedTemplate',
        ),
        migrations.DeleteModel(
            name='LedTemplateItem',
        ),
        migrations.DeleteModel(
            name='MultimediaTemplate',
        ),
        migrations.DeleteModel(
            name='MultimediaTemplateItem',
        ),
        migrations.DeleteModel(
            name='ShieldTemplate',
        ),
        migrations.DeleteModel(
            name='ShieldTemplateItem',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
    ]
