# Generated by Django 6.0.1 on 2026-02-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ledshieldtemplate_remove_templateitem_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
    ]
