# Generated by Django 6.0.1 on 2026-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shield_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='financial_notes',
            field=models.TextField(blank=True, verbose_name='Финансовые заметки'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_external_estimate',
            field=models.TextField(blank=True, verbose_name='Смета контрагента'),
        ),
    ]
