# Generated by Django 6.0.1 on 2026-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_financial_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_external_estimate', models.TextField(blank=True, verbose_name='Смета контрагента')),
                ('financial_notes', models.TextField(blank=True, verbose_name='Финансовые заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Финансовые настройки',
                'verbose_name_plural': 'Финансовые настройки',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='financial_notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partner_external_estimate',
        ),
    ]
