# Generated by Django 6.0.1 on 2026-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_stage_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='category',
            field=models.CharField(choices=[('PROJECT', 'Проект и схемы'), ('WORK', 'Реализация (Этапы 1-2)'), ('FINISH', 'Финишные фото')], default='PROJECT', max_length=20, verbose_name='Категория'),
        ),
    ]
