# Generated by Django 6.0.1 on 2026-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_projectfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_files/%Y/%m/', verbose_name='Файл'),
        ),
    ]
