# Generated by Django 6.0.1 on 2026-02-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя'),
        ),
    ]
