# Generated by Django 5.2.11 on 2026-02-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_projectfile_original_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectorySection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код раздела")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Раздел справочника",
                "verbose_name_plural": "Разделы справочника",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, verbose_name="Код")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.directorysection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция справочника",
                "verbose_name_plural": "Позиции справочника",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "code"),
                        name="unique_directory_entry_code_in_section",
                    )
                ],
            },
        ),
    ]
